version: '3.1'
services:
  api_service:
    image: 'spring-api:latest'
#    build: ./docker/api_spring
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - postgres_data
    links:
      - postgres_data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_data/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=p34kleiorntk09kslQ
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres_data:
    image: 'postgres_data:latest'
    container_name: db
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=p34kleiorntk09kslQ
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5